spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ems
    username: postgres
    password: "*Mareen7#"
    driver-class-name: 
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    
